# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#
# TODO(franklinn): Stop tagging java/mvn images once usage has dropped off.

steps:
# run examples

- name: 'gcr.io/$PROJECT_ID/mvn:3.5.0-jdk-8'
  args: ['sonar:sonar']
  dir: 'sonarqube-scanner-maven'

